language: node_js
node_js:
  - "6"
  - "7"
  - "node"
before_script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - yarn run bootstrap:slow && yarn run build
script: yarn test
notifications:
  email: false
